version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs/docs-requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/src/conf.py
