name: Run Tests for PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py-ver:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-ver }}
          cache: pip
      - name: install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pytest
          python -m pip install .
      - name: run tests
        run: |
          python -m pytest tests/
